# Generated by Django 3.0.5 on 2020-05-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200518_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='discount'),
            preserve_default=False,
        ),
    ]
