# Generated by Django 3.0.5 on 2020-05-19 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
        ('product', '0005_auto_20200518_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bestseller',
            field=models.BooleanField(default=False, verbose_name='bestselletr'),
        ),
        migrations.AlterField(
            model_name='product',
            name='new',
            field=models.BooleanField(default=True, verbose_name='new product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prdbrand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.Brand', verbose_name='brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prdcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='product url'),
        ),
    ]
