# Generated by Django 3.0.5 on 2020-05-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BrdName', models.CharField(max_length=50)),
                ('brdDesc', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VarName', models.CharField(max_length=50)),
                ('VarDesc', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'variant',
                'verbose_name_plural': 'variants',
            },
        ),
    ]
